/*
 * MonsterView.java
 */

package GUI;

import NapakalakiGame.Monster;
import javax.swing.JPanel;

/**
 * Representa la vista de un monstruo.
 */
public class MonsterView extends JPanel {
    
    private Monster monsterModel;

    public MonsterView() {
        initComponents();
    }
    
    public void setMonster(Monster monster) {
        monsterModel = monster; 
        
        this.name.setText(monsterModel.getName());
        this.level.setText(Integer.toString(monsterModel.getCombatLevel()));
        this.cultistLevel.setText(Integer.toString( 
                monsterModel.getCombatLevelAgainstCultistPlayer()));
        this.prizeView.setPrize(monsterModel.getPrize());
        this.badConsequenceView.setBadConsequence(monsterModel.getBadConsequence());
        
        revalidate();
        repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nameLabel = new javax.swing.JLabel();
        name = new javax.swing.JLabel();
        levelLabel = new javax.swing.JLabel();
        level = new javax.swing.JLabel();
        prizeLabel = new javax.swing.JLabel();
        badConsequenceLabel = new javax.swing.JLabel();
        prizeView = new GUI.PrizeView();
        badConsequenceView = new GUI.BadConsequenceView();
        cultistLevel = new javax.swing.JLabel();
        cultistLevelLabel = new javax.swing.JLabel();

        nameLabel.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        nameLabel.setText("Nombre:");

        name.setText("Nombre del monstruo");

        levelLabel.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        levelLabel.setText("Nivel:");

        level.setText("Nivel del monstruo");

        prizeLabel.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        prizeLabel.setText("Premio:");

        badConsequenceLabel.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        badConsequenceLabel.setText("Mal rollo:");

        cultistLevel.setText("Nivel contra sectarios");

        cultistLevelLabel.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        cultistLevelLabel.setText("Nivel contra sectarios:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(badConsequenceView, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(badConsequenceLabel)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nameLabel)
                            .addComponent(levelLabel)
                            .addComponent(cultistLevelLabel))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(level)
                            .addComponent(name)
                            .addComponent(cultistLevel)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(prizeLabel)
                        .addGap(18, 18, 18)
                        .addComponent(prizeView, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(8, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nameLabel)
                    .addComponent(name))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(levelLabel)
                    .addComponent(level))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cultistLevelLabel)
                    .addComponent(cultistLevel))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(prizeLabel)
                    .addComponent(prizeView, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(badConsequenceLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(badConsequenceView, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel badConsequenceLabel;
    private GUI.BadConsequenceView badConsequenceView;
    private javax.swing.JLabel cultistLevel;
    private javax.swing.JLabel cultistLevelLabel;
    private javax.swing.JLabel level;
    private javax.swing.JLabel levelLabel;
    private javax.swing.JLabel name;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JLabel prizeLabel;
    private GUI.PrizeView prizeView;
    // End of variables declaration//GEN-END:variables
}
